services:
  next-app:
    build:
      context: .
      # dockerfile: prod.Dockerfile
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL}
      - VIRTUAL_HOST=stats.colombiaredessociales.com
      - LETSENCRYPT_HOST=stats.colombiaredessociales.com
      - LETSENCRYPT_EMAIL=info@windowschannel.com
    volumes:
      - ./:/app/
      - ./public:/app/public
    expose:
      - "3000"
    networks:
      - app-network

networks:
  app-network:
    external: true