version: "3"

services:
  next-app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env 
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    networks:
      - social-stats-network

networks:
  social-stats-network:
    external: true