services:
  next-app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      API_URL: ${API_URL}
    networks:
      - social-stats-network

networks:
  social-stats-network:
    external: true