services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    # Set environment variables directly in the docker-compose file
    restart: always
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_URL=${API_URL}
    volumes:
      - ./:/app/
      - ./public:/app/public
    ports:
      - 3000:3000
    networks:
      - app-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app-network:
    external: true