version: "3"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./:/app/
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - social-stats-network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  social-stats-network:
    external: true